# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/

# The URL of your website.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://mooncaker816.github.io/"


# Enable analytics by entering your Google Analytics tracking ID
# googleAnalytics = ""
googleAnalytics = "UA-118085755-1"

[params]

  sumositeid = "179bbb944edcce8627cb15d8b33fadaf440e3b5043efd79feb50582c0be37fb2"

